name: xtudo
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  
  #Firebase
  firebase_auth: ^3.3.10
  cloud_firestore: ^3.1.10
  firebase_core: ^1.13.1
  firebase_analytics: ^9.1.2
  firebase_database: ^9.0.8

  #login
  google_sign_in: ^5.2.4
  flutter_facebook_auth: ^4.1.1

  #desing
  cupertino_icons: ^1.0.2
  flutter_login: ^3.2.0
  provider: ^6.0.2
  google_fonts: ^2.3.1
  curved_navigation_bar: ^1.0.2
  material_design_icons_flutter: any

  #seguranca
  mask_text_input_formatter: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  
  flutter_lints: ^1.0.0


flutter:

 
  uses-material-design: true


  assets:
    - images/
    - images/logoG.png   

  